/* automatically generated by configure */
/* edit configure.ac to change version number */
#define CRX_MAJOR_VERSION 8
#define CRX_MINOR_VERSION 3
#define CRX_RELEASE_VERSION 0
#define CRX_EXTRA_VERSION ""
#define CRX_VERSION "8.3.0"
#define CRX_VERSION_ID 80300
