/* This is a generated file, edit the .stub.crx file instead.
 * Stub hash: 58c8b6ec69650d241919ebba4f957b4b141fb9f2 */



static void register_main_symbols(int module_number)
{
	REGISTER_STRING_CONSTANT("CRX_VERSION", CRX_VERSION, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("CRX_MAJOR_VERSION", CRX_MAJOR_VERSION, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("CRX_MINOR_VERSION", CRX_MINOR_VERSION, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("CRX_RELEASE_VERSION", CRX_RELEASE_VERSION, CONST_PERSISTENT);
	REGISTER_STRING_CONSTANT("CRX_EXTRA_VERSION", CRX_EXTRA_VERSION, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("CRX_VERSION_ID", CRX_VERSION_ID, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("CRX_ZTS", CRX_ZTS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("CRX_DEBUG", CRX_DEBUG, CONST_PERSISTENT);
	REGISTER_STRING_CONSTANT("CRX_OS", CRX_OS_STR, CONST_PERSISTENT);
	REGISTER_STRING_CONSTANT("CRX_OS_FAMILY", CRX_OS_FAMILY, CONST_PERSISTENT);
	REGISTER_STRING_CONSTANT("DEFAULT_INCLUDE_PATH", CRX_INCLUDE_PATH, CONST_PERSISTENT);
	REGISTER_STRING_CONSTANT("PEAR_INSTALL_DIR", PEAR_INSTALLDIR, CONST_PERSISTENT);
	REGISTER_STRING_CONSTANT("PEAR_EXTENSION_DIR", CRX_EXTENSION_DIR, CONST_PERSISTENT);
	REGISTER_STRING_CONSTANT("CRX_EXTENSION_DIR", CRX_EXTENSION_DIR, CONST_PERSISTENT);
	REGISTER_STRING_CONSTANT("CRX_PREFIX", CRX_PREFIX, CONST_PERSISTENT);
	REGISTER_STRING_CONSTANT("CRX_BINDIR", CRX_BINDIR, CONST_PERSISTENT);
#if !defined(CRX_WIN32)
	REGISTER_STRING_CONSTANT("CRX_MANDIR", CRX_MANDIR, CONST_PERSISTENT);
#endif
	REGISTER_STRING_CONSTANT("CRX_LIBDIR", CRX_LIBDIR, CONST_PERSISTENT);
	REGISTER_STRING_CONSTANT("CRX_DATADIR", CRX_DATADIR, CONST_PERSISTENT);
	REGISTER_STRING_CONSTANT("CRX_SYSCONFDIR", CRX_SYSCONFDIR, CONST_PERSISTENT);
	REGISTER_STRING_CONSTANT("CRX_LOCALSTATEDIR", CRX_LOCALSTATEDIR, CONST_PERSISTENT);
	REGISTER_STRING_CONSTANT("CRX_CONFIG_FILE_PATH", CRX_CONFIG_FILE_PATH, CONST_PERSISTENT);
	REGISTER_STRING_CONSTANT("CRX_CONFIG_FILE_SCAN_DIR", CRX_CONFIG_FILE_SCAN_DIR, CONST_PERSISTENT);
	REGISTER_STRING_CONSTANT("CRX_SHLIB_SUFFIX", CRX_SHLIB_SUFFIX, CONST_PERSISTENT);
	REGISTER_STRING_CONSTANT("CRX_EOL", CRX_EOL, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("CRX_MAXPATHLEN", MAXPATHLEN, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("CRX_INT_MAX", CREX_LONG_MAX, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("CRX_INT_MIN", CREX_LONG_MIN, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("CRX_INT_SIZE", SIZEOF_CREX_LONG, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("CRX_FD_SETSIZE", FD_SETSIZE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("CRX_FLOAT_DIG", DBL_DIG, CONST_PERSISTENT);
	REGISTER_DOUBLE_CONSTANT("CRX_FLOAT_EPSILON", DBL_EPSILON, CONST_PERSISTENT);
	REGISTER_DOUBLE_CONSTANT("CRX_FLOAT_MAX", DBL_MAX, CONST_PERSISTENT);
	REGISTER_DOUBLE_CONSTANT("CRX_FLOAT_MIN", DBL_MIN, CONST_PERSISTENT);
#if defined(CRX_WIN32)
	REGISTER_LONG_CONSTANT("CRX_WINDOWS_VERSION_MAJOR", EG(windows_version_info).dwMajorVersion, CONST_PERSISTENT);
#endif
#if defined(CRX_WIN32)
	REGISTER_LONG_CONSTANT("CRX_WINDOWS_VERSION_MINOR", EG(windows_version_info).dwMinorVersion, CONST_PERSISTENT);
#endif
#if defined(CRX_WIN32)
	REGISTER_LONG_CONSTANT("CRX_WINDOWS_VERSION_BUILD", EG(windows_version_info).dwBuildNumber, CONST_PERSISTENT);
#endif
#if defined(CRX_WIN32)
	REGISTER_LONG_CONSTANT("CRX_WINDOWS_VERSION_PLATFORM", EG(windows_version_info).dwPlatformId, CONST_PERSISTENT);
#endif
#if defined(CRX_WIN32)
	REGISTER_LONG_CONSTANT("CRX_WINDOWS_VERSION_SP_MAJOR", EG(windows_version_info).wServicePackMajor, CONST_PERSISTENT);
#endif
#if defined(CRX_WIN32)
	REGISTER_LONG_CONSTANT("CRX_WINDOWS_VERSION_SP_MINOR", EG(windows_version_info).wServicePackMinor, CONST_PERSISTENT);
#endif
#if defined(CRX_WIN32)
	REGISTER_LONG_CONSTANT("CRX_WINDOWS_VERSION_SUITEMASK", EG(windows_version_info).wSuiteMask, CONST_PERSISTENT);
#endif
#if defined(CRX_WIN32)
	REGISTER_LONG_CONSTANT("CRX_WINDOWS_VERSION_PRODUCTTYPE", EG(windows_version_info).wProductType, CONST_PERSISTENT);
#endif
#if defined(CRX_WIN32)
	REGISTER_LONG_CONSTANT("CRX_WINDOWS_NT_DOMAIN_CONTROLLER", VER_NT_DOMAIN_CONTROLLER, CONST_PERSISTENT);
#endif
#if defined(CRX_WIN32)
	REGISTER_LONG_CONSTANT("CRX_WINDOWS_NT_SERVER", VER_NT_SERVER, CONST_PERSISTENT);
#endif
#if defined(CRX_WIN32)
	REGISTER_LONG_CONSTANT("CRX_WINDOWS_NT_WORKSTATION", VER_NT_WORKSTATION, CONST_PERSISTENT);
#endif
	REGISTER_LONG_CONSTANT("CRX_OUTPUT_HANDLER_START", CRX_OUTPUT_HANDLER_START, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("CRX_OUTPUT_HANDLER_WRITE", CRX_OUTPUT_HANDLER_WRITE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("CRX_OUTPUT_HANDLER_FLUSH", CRX_OUTPUT_HANDLER_FLUSH, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("CRX_OUTPUT_HANDLER_CLEAN", CRX_OUTPUT_HANDLER_CLEAN, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("CRX_OUTPUT_HANDLER_FINAL", CRX_OUTPUT_HANDLER_FINAL, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("CRX_OUTPUT_HANDLER_CONT", CRX_OUTPUT_HANDLER_WRITE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("CRX_OUTPUT_HANDLER_END", CRX_OUTPUT_HANDLER_FINAL, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("CRX_OUTPUT_HANDLER_CLEANABLE", CRX_OUTPUT_HANDLER_CLEANABLE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("CRX_OUTPUT_HANDLER_FLUSHABLE", CRX_OUTPUT_HANDLER_FLUSHABLE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("CRX_OUTPUT_HANDLER_REMOVABLE", CRX_OUTPUT_HANDLER_REMOVABLE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("CRX_OUTPUT_HANDLER_STDFLAGS", CRX_OUTPUT_HANDLER_STDFLAGS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("CRX_OUTPUT_HANDLER_STARTED", CRX_OUTPUT_HANDLER_STARTED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("CRX_OUTPUT_HANDLER_DISABLED", CRX_OUTPUT_HANDLER_DISABLED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("UPLOAD_ERR_OK", CRX_UPLOAD_ERROR_OK, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("UPLOAD_ERR_INI_SIZE", CRX_UPLOAD_ERROR_A, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("UPLOAD_ERR_FORM_SIZE", CRX_UPLOAD_ERROR_B, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("UPLOAD_ERR_PARTIAL", CRX_UPLOAD_ERROR_C, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("UPLOAD_ERR_NO_FILE", CRX_UPLOAD_ERROR_D, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("UPLOAD_ERR_NO_TMP_DIR", CRX_UPLOAD_ERROR_E, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("UPLOAD_ERR_CANT_WRITE", CRX_UPLOAD_ERROR_F, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("UPLOAD_ERR_EXTENSION", CRX_UPLOAD_ERROR_X, CONST_PERSISTENT);
}
