fuzzer: $(CRX_FUZZER_BINARIES)

FUZZER_BUILD = $(LIBTOOL) --mode=link $(FUZZING_CC) -export-dynamic $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(EXTRA_LDFLAGS_PROGRAM) $(LDFLAGS) $(CRX_RPATHS) $(CRX_GLOBAL_OBJS) $(CRX_BINARY_OBJS) $(EXTRA_LIBS) $(CREX_EXTRA_LIBS) $(FUZZING_LIB)

$(SAPI_FUZZER_PATH)/crx-fuzz-parser: $(CRX_GLOBAL_OBJS) $(CRX_SAPI_OBJS) $(CRX_FUZZER_PARSER_OBJS)
	$(FUZZER_BUILD) $(CRX_FUZZER_PARSER_OBJS) -o $@

$(SAPI_FUZZER_PATH)/crx-fuzz-execute: $(CRX_GLOBAL_OBJS) $(CRX_SAPI_OBJS) $(CRX_FUZZER_EXECUTE_OBJS)
	$(FUZZER_BUILD) $(CRX_FUZZER_EXECUTE_OBJS) -o $@

$(SAPI_FUZZER_PATH)/crx-fuzz-function-jit: $(CRX_GLOBAL_OBJS) $(CRX_SAPI_OBJS) $(CRX_FUZZER_FUNCTION_JIT_OBJS)
	$(FUZZER_BUILD) $(CRX_FUZZER_FUNCTION_JIT_OBJS) -o $@

$(SAPI_FUZZER_PATH)/crx-fuzz-tracing-jit: $(CRX_GLOBAL_OBJS) $(CRX_SAPI_OBJS) $(CRX_FUZZER_TRACING_JIT_OBJS)
	$(FUZZER_BUILD) $(CRX_FUZZER_TRACING_JIT_OBJS) -o $@

$(SAPI_FUZZER_PATH)/crx-fuzz-unserialize: $(CRX_GLOBAL_OBJS) $(CRX_SAPI_OBJS) $(CRX_FUZZER_UNSERIALIZE_OBJS)
	$(FUZZER_BUILD) $(CRX_FUZZER_UNSERIALIZE_OBJS) -o $@

$(SAPI_FUZZER_PATH)/crx-fuzz-unserializehash: $(CRX_GLOBAL_OBJS) $(CRX_SAPI_OBJS) $(CRX_FUZZER_UNSERIALIZEHASH_OBJS)
	$(FUZZER_BUILD) $(CRX_FUZZER_UNSERIALIZEHASH_OBJS) -o $@

$(SAPI_FUZZER_PATH)/crx-fuzz-json: $(CRX_GLOBAL_OBJS) $(CRX_SAPI_OBJS) $(CRX_FUZZER_JSON_OBJS)
	$(FUZZER_BUILD) $(CRX_FUZZER_JSON_OBJS) -o $@

$(SAPI_FUZZER_PATH)/crx-fuzz-exif: $(CRX_GLOBAL_OBJS) $(CRX_SAPI_OBJS) $(CRX_FUZZER_EXIF_OBJS)
	$(FUZZER_BUILD) $(CRX_FUZZER_EXIF_OBJS) -o $@

$(SAPI_FUZZER_PATH)/crx-fuzz-mbstring: $(CRX_GLOBAL_OBJS) $(CRX_SAPI_OBJS) $(CRX_FUZZER_MBSTRING_OBJS)
	$(FUZZER_BUILD) $(CRX_FUZZER_MBSTRING_OBJS) -o $@

$(SAPI_FUZZER_PATH)/crx-fuzz-mbregex: $(CRX_GLOBAL_OBJS) $(CRX_SAPI_OBJS) $(CRX_FUZZER_MBREGEX_OBJS)
	$(FUZZER_BUILD) $(CRX_FUZZER_MBREGEX_OBJS) -o $@
