name: Verify generated files are up to date
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -x
        [[ "$OSTYPE" == "darwin"* ]] && export PATH="/usr/local/opt/bison/bin:$PATH"
        scripts/dev/credits
        scripts/dev/genfiles
        Crex/crex_vm_gen.crx
        ext/tokenizer/tokenizer_data_gen.crx
        build/gen_stub.crx -f
        build/gen_stub.crx --generate-optimizer-info
        git add . -N && git diff --exit-code
