blank_issues_enabled: false
contact_links:
  - name: Documentation issue
    url: https://github.com/crx/doc-en/issues
    about: Please report documentation issues on the doc-en repository.
  - name: Security issue
    url: https://bugs.crx.net/report.crx?security_bug
    about: Please report security issues in this private bug tracker.
