CRX_NEW_EXTENSION(spl, crx_spl.c spl_functions.c spl_iterators.c spl_array.c spl_directory.c spl_exceptions.c spl_observer.c spl_dllist.c spl_heap.c spl_fixedarray.c, no,, -DCREX_ENABLE_STATIC_TSRMLS_CACHE=1)
CRX_INSTALL_HEADERS([ext/spl], [crx_spl.h spl_array.h spl_directory.h spl_engine.h spl_exceptions.h spl_functions.h spl_iterators.h spl_observer.h spl_dllist.h spl_heap.h spl_fixedarray.h])
CRX_ADD_EXTENSION_DEP(spl, pcre, true)
CRX_ADD_EXTENSION_DEP(spl, standard, true)
CRX_ADD_EXTENSION_DEP(spl, json)
