/* This is a generated file, edit the .stub.crx file instead.
 * Stub hash: 9198095c858c95fcb31252ddfa24fe04787d0460 */



static void register_userspace_symbols(int module_number)
{
	REGISTER_LONG_CONSTANT("STREAM_USE_PATH", USE_PATH, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_IGNORE_URL", IGNORE_URL, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_REPORT_ERRORS", REPORT_ERRORS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_MUST_SEEK", STREAM_MUST_SEEK, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_URL_STAT_LINK", CRX_STREAM_URL_STAT_LINK, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_URL_STAT_QUIET", CRX_STREAM_URL_STAT_QUIET, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_MKDIR_RECURSIVE", CRX_STREAM_MKDIR_RECURSIVE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_IS_URL", CRX_STREAM_IS_URL, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_OPTION_BLOCKING", CRX_STREAM_OPTION_BLOCKING, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_OPTION_READ_TIMEOUT", CRX_STREAM_OPTION_READ_TIMEOUT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_OPTION_READ_BUFFER", CRX_STREAM_OPTION_READ_BUFFER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_OPTION_WRITE_BUFFER", CRX_STREAM_OPTION_WRITE_BUFFER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_BUFFER_NONE", CRX_STREAM_BUFFER_NONE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_BUFFER_LINE", CRX_STREAM_BUFFER_LINE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_BUFFER_FULL", CRX_STREAM_BUFFER_FULL, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_CAST_AS_STREAM", CRX_STREAM_AS_STDIO, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_CAST_FOR_SELECT", CRX_STREAM_AS_FD_FOR_SELECT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_META_TOUCH", CRX_STREAM_META_TOUCH, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_META_OWNER", CRX_STREAM_META_OWNER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_META_OWNER_NAME", CRX_STREAM_META_OWNER_NAME, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_META_GROUP", CRX_STREAM_META_GROUP, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_META_GROUP_NAME", CRX_STREAM_META_GROUP_NAME, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_META_ACCESS", CRX_STREAM_META_ACCESS, CONST_PERSISTENT);
}
